name: later
description: A starter template for a macos tool application.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  libsql_client: ^0.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.1.3
  http: ^1.2.1
  html: ^0.15.4
  flutter_cache_manager: ^3.3.1
  macos_ui: ^2.1.10
  shared_preferences: ^2.0.17
  file_picker: ^9.0.2
  path: ^1.8.3
  path_provider: ^2.1.2
  pubspec_parse: ^1.2.1
  intl: ^0.19.0
  uuid: ^4.3.3
  system_tray: ^0.1.1
  url_launcher: ^6.2.4
  uni_links: ^0.5.1
  window_manager: ^0.4.3
  local_notifier: ^0.1.6
  meta: ^1.9.1
  csv: ^5.1.1
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/
    - assets/icons/
